export interface Map { [key: number]: string };

export const INT_MAP: Map = {
  0: 'zero',
  1: 'one',
  2: 'two',
  3: 'three',
  4: 'four',
  5: 'five',
  6: 'six',
  7: 'seven',
  8: 'eight',
  9: 'nine',
  10: 'ten',
  11: 'eleven',
  12: 'twelve',
  13: 'thirteen',
  14: 'fourteen',
  15: 'fiveteen',
  16: 'sixteen',
  17: 'seventeen',
  18: 'eighteen',
  19: 'nineteen',
  20: 'twenty',
  30: 'thirty',
  40: 'fourty',
  50: 'fifty',
  60: 'sixty',
  70: 'seventy',
  80: 'eighty',
  90: 'ninety',
}

export const INT_LABEL_MAP = {
  0: 'hundred',
  1: 'thousand',
  2: 'million',
  3: 'milliard',
  4: 'billion',
  5: 'billiard',
  6: 'trillion',
  7: 'trilliard',
}
